### ISSUE TITLE
When initialize database , I'm getting "TypeError: documents must be a non-empty list" error

### ISSUE THREAD

**Issue by tmddnr5410** [eliasgranderubio/dagda#107]
### **Short description**
Evaluate Dagda. for image scan , 

### **Reproduction steps**
Follow every step (pre-requisites) to install and start dagda:
Python3, MongoDB, Docker are higher versions than listed.
Installed all the requirements using pip3
Installed kernel-headers
Installed sysdig
Used sudo to install all the above packages

sudo python3 dagda.py start -d
sudo python3 dagda.py vuln --init'

**I tried adding ram to solve the problem, running it on another PC, and also using AWS EC2. But I get the same error from the program every tim**e.

**### Expected results**
Get a working state of the database.

### **Actual results**
TypeError occurred: ('documents must be a non-empty list',)

**### On which platforms did you notice this:**
Please complete the following information:

- OS: Ubuntu 20.04
- Docker version: Latest

### **Backtrace**
Unexpected exception of type TypeError occured: ('documents must be a non-empty list' )
[docker.log](https://github.com/eliasgranderubio/dagda/files/7375849/docker.log)

 <ERROR> <DagdaServer> <dagda_server> <_init_or_update_db:155> <Unexpected exception of type TypeError occurred: ('documents must be a non-empty list',)>
Traceback (most recent call last):
  File "/home/kupfer/git/dagda/dagda/api/dagda_server.py", line 150, in _init_or_update_db
    db_composer.compose_vuln_db()
  File "/home/kupfer/git/dagda/dagda/vulnDB/db_composer.py", line 92, in compose_vuln_db
    self.mongoDbDriver.bulk_insert_rhsa(rhsa_list)
  File "/home/kupfer/git/dagda/dagda/driver/mongodb_driver.py", line 112, in bulk_insert_rhsa
    self.db.rhsa.insert_many(rhsa_list)
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 755, in insert_many
    raise TypeError("documents must be a non-empty list")
TypeError: documents must be a non-empty list

**I tried adding ram to solve the problem, running it on another PC, and also using AWS EC2. But I get the same error from the program every time**.

**Comment by 6AlexMan** [comment]
> ### **Short description**
> 
> Evaluate Dagda. for image scan ,
> 
> ### **Reproduction steps**
> 
> Follow every step (pre-requisites) to install and start dagda: Python3, MongoDB, Docker are higher versions than listed. Installed all the requirements using pip3 Installed kernel-headers Installed sysdig Used sudo to install all the above packages
> 
> sudo python3 dagda.py start -d sudo python3 dagda.py vuln --init'
> 
> **I tried adding ram to solve the problem, running it on another PC, and also using AWS EC2. But I get the same error from the program every tim**e.
> 
> **### Expected results** Get a working state of the database.
> 
> ### **Actual results**
> 
> TypeError occurred: ('documents must be a non-empty list',)
> 
> **### On which platforms did you notice this:** Please complete the following information:
> 
> * OS: Ubuntu 20.04
> * Docker version: Latest
> 
> ### **Backtrace**
> 
> Unexpected exception of type TypeError occured: ('documents must be a non-empty list' ) [docker.log](https://github.com/eliasgranderubio/dagda/files/7375849/docker.log)
> 
> <dagda_server> <_init_or_update_db:155> <Unexpected exception of type TypeError occurred: ('documents must be a non-empty list',)> Traceback (most recent call last): File "/home/kupfer/git/dagda/dagda/api/dagda_server.py", line 150, in _init_or_update_db db_composer.compose_vuln_db() File "/home/kupfer/git/dagda/dagda/vulnDB/db_composer.py", line 92, in compose_vuln_db self.mongoDbDriver.bulk_insert_rhsa(rhsa_list) File "/home/kupfer/git/dagda/dagda/driver/mongodb_driver.py", line 112, in bulk_insert_rhsa self.db.rhsa.insert_many(rhsa_list) File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 755, in insert_many raise TypeError("documents must be a non-empty list") TypeError: documents must be a non-empty list
> 
> **I tried adding ram to solve the problem, running it on another PC, and also using AWS EC2. But I get the same error from the program every time**.

https://github.com/eliasgranderubio/dagda/issues/109#issuecomment-2899654747

**Comment by 6AlexMan** [comment]
you can `python3 dagda.py vuln --init_status` to check db init status.
:)
