### ISSUE TITLE
Vulnerabilities database is not being populated

### ISSUE THREAD

**Issue by igorshmukler** [eliasgranderubio/dagda#32]
### Short description

I was trying to test `dagda`.

'dagda.py vuln --product openldap --product_version 2.2.20'

### Reproduction steps

0. Started mongo with `docker run -d -p 27017:27017 mongo`.
0.1. Checked mongo is running with:
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
4c71cbb9f6b4        mongo               "docker-entrypoint.s…"   About an hour ago   Up About an hour    0.0.0.0:27017->27017/tcp   dreamy_snyder
```
1. Start Dagda server as 'python3 dagda.py start'
1.1. The command never returns. The server seems to be running.
2. From another shell session, export environmental variables then type the Dagda CLI command 'python3 dagda.py vuln --init'
2.1. Init returns immediately.
2.2. Connecting to the mongo shows:
```
> show databases;
admin          0.000GB
config         0.000GB
local          0.000GB
vuln_database  0.000GB
```
then
```
> use vuln_database
switched to db vuln_database
> db.init_db_process_status.find()
{ "_id" : ObjectId("5b190d4e1d41c82b38d1462b"), "timestamp" : 1528368462.684211, "status" : "Initializing" }
>
```
3. Execute: 'python3 dagda.py vuln --product openldap --product_version 2.2.20'
4. See response:
```
{
    "err": 500,
    "msg": "Internal Server Error"
}
```
### Expected results

I expected to see the report as shown in README would be printed out.

### Actual results

```
{
    "err": 500,
    "msg": "Internal Server Error"
}
```

### On which platforms did you notice this:

Please complete the following information:

 - OS: Ubuntu
 - OS Version: `Linux ubuntu 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
 - Python version: `Python 3.5.2`
 - Docker version: `18.03.1-ce, build 9ee9f40`
 - MongoDB version: `3.6.5`

### Backtrace

```
[2018-06-08 09:16:30,739] ERROR in app: Exception on /v1/vuln/products/openldap/2.2.20 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shmukler/dagda/dagda/api/service/vuln.py", line 57, in get_vulns_by_product_and_version
    vulns = InternalServer.get_mongodb_driver().get_vulnerabilities(product, version)
  File "/home/shmukler/dagda/dagda/driver/mongodb_driver.py", line 325, in get_vulnerabilities
    for bid in bid_cursor:
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 1090, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 1012, in _refresh
    self.__read_concern))
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 905, in __send_message
    helpers._check_command_response(doc['data'][0])
  File "/usr/local/lib/python3.5/dist-packages/pymongo/helpers.py", line 205, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: text index required for $text query (no such collection 'vuln_database.bid')
<2018-06-08 09:16:30,739> <ERROR> <DagdaServer> <app> <Exception on /v1/vuln/products/openldap/2.2.20 [GET]>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shmukler/dagda/dagda/api/service/vuln.py", line 57, in get_vulns_by_product_and_version
    vulns = InternalServer.get_mongodb_driver().get_vulnerabilities(product, version)
  File "/home/shmukler/dagda/dagda/driver/mongodb_driver.py", line 325, in get_vulnerabilities
    for bid in bid_cursor:
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 1090, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 1012, in _refresh
    self.__read_concern))
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 905, in __send_message
    helpers._check_command_response(doc['data'][0])
  File "/usr/local/lib/python3.5/dist-packages/pymongo/helpers.py", line 205, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: text index required for $text query (no such collection 'vuln_database.bid')
```

### Solution

Not known

**Comment by eliasgranderubio** [comment]
Hi @igorshmukler ,

If you want use Dagda you must follow the next step

* Step 1. Start Dagda server --> `python3 dagda.py start`

* Step 2. Run init database process --> `python3 dagda.py vuln --init`
(This process run in async way so you must run the Step 3 until the status is set to **Updated**).

* Step 3. Check init database process until it ends --> `python3 dagda.py vuln --init_status`

Keep in mind that the init process depends on network and can take several minutes for finishing so be patient.

**Comment by igorshmukler** [comment]
Hello @eliasgranderubio ,

Thank you for a prompt response.

If I check the status of the init after starting `dagda`, before the `init` command, it returns:
```
{
    "status": "None",
    "timestamp": "-"
}
```
After I issue `init` the output changes to:
```
{
    "status": "Initializing",
    "timestamp": "2018-06-11 05:55:06.678793"
}
```
Timestamp never changes, nor the status. Seems like it returns what I see with the mongo client by running: `init_db_process_status.find()` albeit with the convenience of the CLI.

Is there something that I could check? Would any additional information be relevant to figure out what I am doing wrong? I do see that `start` spins-up the `falco` image and `dagda` seems to be almost working, for me. As if something small was messing things up...

Thank you.

**Comment by eliasgranderubio** [comment]
I've just testing several times the population of the VulnDB and for me works fine.

Anyway, I have enanced debug logging for trying to identify the error. Please @chandrakantnial , clean your mongoDB collections, start Dagda server with `python3 dagda.py start -d`, and then rerun the steps #2 and #3.

Update me with the feedback that you get if the issue persists.

**Comment by eliasgranderubio** [comment]
That looks like a performance issue because your machine are starvating. How much RAM has your computer? I always run Dagda in a machine with at least 4 GB.

You can reduce n_jobs from 100 to another minor number in the next line: 
* [bid_downloader.py:L111](https://github.com/eliasgranderubio/dagda/blob/master/dagda/vulnDB/bid_downloader.py#L111) 

Please, let me know your computer specifications for trying to fix this performance issue.

**Comment by eliasgranderubio** [comment]
@chandrakantnial Have you any update? Could you give me feedback about?

**Comment by eliasgranderubio** [comment]
I update the milestone for this issue. 

@chandrakantnial , have you any update about this bug for trying fix it?

**Comment by eliasgranderubio** [comment]
After two months without any update I understand the bug never appeared again so I close this issue.

If the issue persists, please, reopen this issue again.

**Comment by SaurabhDev** [comment]
Issue still persist ... vuln_db size is zero
