### ISSUE TITLE
uncaught exception in _untar_layers

### ISSUE THREAD

**Issue by DrGruby** [eliasgranderubio/dagda#36]
### Short description

I was trying to test ubuntu:16.04

### Reproduction steps

1. Start Dagda server with the debug parameter ( `python3 dagda.py start -d` )
2. Type the Dagda CLI command `python3 dagda.py check --docker_image ubuntu:16.04` 

### Expected results

I expected that by analyzing the docker image ubuntu:16.04 and showing the report.

### Actual results

Instead of a report, what I saw was that error `Unexpected exception of type PermissionError occured: (1, 'Operation not permitted')` 

### On which platforms did you notice this:

Please complete the following information:

 - OS: Ubuntu
 - OS Version: `Linux PC 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
 - Python version: `Python 3.6.5`
 - Docker version` Docker version 17.12.1-ce, build 7390fc6`
 - MongoDB version 2.6.12

### Backtrace

```
<2018-09-20 18:59:59,109> <ERROR> <DagdaServer> <analyzer> <evaluate_image:108> <Unexpected exception of type PermissionError occured: (1, 'Operation not permitted')>
Traceback (most recent call last):
  File "$HOME/dagda/dagda/analysis/analyzer.py", line 74, in evaluate_image
    image_name=image_name)
  File "$HOME/dagda/dagda/analysis/static/util/utils.py", line 47, in extract_filesystem_bundle
    _untar_layers(temporary_dir, layers)
  File "$HOME/dagda/dagda/analysis/static/util/utils.py", line 82, in _untar_layers
    tarfile.extract(output[member_name], path=dir, set_attrs=False)
  File "/usr/lib/python3.6/tarfile.py", line 2050, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.6/tarfile.py", line 2126, in _extract_member
    self.makedev(tarinfo, targetpath)
  File "/usr/lib/python3.6/tarfile.py", line 2200, in makedev
    os.makedev(tarinfo.devmajor, tarinfo.devminor))
PermissionError: [Errno 1] Operation not permitted
```

also I make a little modyfication in `dagda/analysis/static/util/utils.py` 
```
def _untar_layers(dir, layers):
    output = {}
    # Untar layer filesystem bundle
    for layer in layers:
        tarfile = TarFile(dir + "/" + layer)
        for member in tarfile.getmembers():
            output[member.name] = member
    for member_name in output:
        try:
            tarfile.extract(output[member_name], path=dir, set_attrs=False)
        except (ValueError, ReadError):
            pass
        except:
            DagdaLogger.get_logger().debug('tar custom: ' + member_name)          

    # Clean up
    for layer in layers:
        clean_up(dir + "/" + layer[:-10])
```
and here is the result of the debug function:
```<2018-09-20 18:58:26,813> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/agpgart>
<2018-09-20 18:58:26,813> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/audio>
<2018-09-20 18:58:26,813> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/audio1>
<2018-09-20 18:58:26,813> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/audio2>
<2018-09-20 18:58:26,813> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/audio3>
<2018-09-20 18:58:26,813> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/audioctl>
<2018-09-20 18:58:26,813> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/console>
<2018-09-20 18:58:26,813> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/dsp>
<2018-09-20 18:58:26,813> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/dsp1>
<2018-09-20 18:58:26,813> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/dsp2>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/dsp3>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/full>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/kmem>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/loop0>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/loop1>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/loop2>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/loop3>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/loop4>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/loop5>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/loop6>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/loop7>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/mem>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/midi0>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/midi00>
<2018-09-20 18:58:26,814> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/midi01>
<2018-09-20 18:58:26,815> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/midi02>
<2018-09-20 18:58:26,815> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/midi03>
<2018-09-20 18:58:26,815> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/midi1>
<2018-09-20 18:58:26,815> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/midi2>
<2018-09-20 18:58:26,815> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/midi3>
<2018-09-20 18:58:26,815> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/mixer>
<2018-09-20 18:58:26,815> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/mixer1>
<2018-09-20 18:58:26,815> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/mixer2>
<2018-09-20 18:58:26,815> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/mixer3>
<2018-09-20 18:58:26,815> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/mpu401data>
<2018-09-20 18:58:26,815> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/mpu401stat>
<2018-09-20 18:58:26,815> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/null>
<2018-09-20 18:58:26,815> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/port>
<2018-09-20 18:58:26,816> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram0>
<2018-09-20 18:58:26,816> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram1>
<2018-09-20 18:58:26,816> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram10>
<2018-09-20 18:58:26,816> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram11>
<2018-09-20 18:58:26,816> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram12>
<2018-09-20 18:58:26,816> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram13>
<2018-09-20 18:58:26,816> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram14>
<2018-09-20 18:58:26,816> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram15>
<2018-09-20 18:58:26,816> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram16>
<2018-09-20 18:58:26,816> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram2>
<2018-09-20 18:58:26,817> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram3>
<2018-09-20 18:58:26,817> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram4>
<2018-09-20 18:58:26,817> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram5>
<2018-09-20 18:58:26,817> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram6>
<2018-09-20 18:58:26,817> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram7>
<2018-09-20 18:58:26,817> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram8>
<2018-09-20 18:58:26,817> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/ram9>
<2018-09-20 18:58:26,817> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/random>
<2018-09-20 18:58:26,817> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/rmidi0>
<2018-09-20 18:58:26,817> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/rmidi1>
<2018-09-20 18:58:26,817> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/rmidi2>
<2018-09-20 18:58:26,817> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/rmidi3>
<2018-09-20 18:58:26,817> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/sequencer>
<2018-09-20 18:58:26,817> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/smpte0>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/smpte1>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/smpte2>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/smpte3>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/sndstat>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/tty>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/tty0>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/tty1>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/tty2>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/tty3>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/tty4>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/tty5>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/tty6>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/tty7>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/tty8>
<2018-09-20 18:58:26,818> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/tty9>
<2018-09-20 18:58:26,819> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/urandom>
<2018-09-20 18:58:26,819> <DEBUG> <DagdaServer> <utils> <_untar_layers:86> <tar custom: dev/zero>
```

### Solution

A possible solution for this issue would be modify the `_untar_layers` function to catch that kind of exception.

**Comment by eliasgranderubio** [comment]
Thank you so much for your reporting, This issue has been fixed with the last commit :-)
