### ISSUE TITLE
docker errors :Multiple IDs found with provided prefix

### ISSUE THREAD

**Issue by axiqia** [eliasgranderubio/dagda#48]
### Short description

I was trying to start Dagda server.

### Reproduction steps
`$ python3 dagda.py start -p 5003 -d`

### Actual results

```
$ python3 dagda.py start -p 5003 -d
Serving on http://localhost:5003
<2019-03-06 21:21:57,188> <ERROR> <DagdaServer> <dagda> <main:46> <500 Server Error: Internal Server Error ("Multiple IDs found with provided prefix: 09b61f6b45dde38ebd925697f418386f8f01ccf3029b08985b65a11eebbcb91e")>
Traceback (most recent call last):
  File "/home/sxue/anaconda3/lib/python3.7/site-packages/docker/api/client.py", line 246, in _raise_for_status
    response.raise_for_status()
  File "/home/sxue/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.37/containers/0/stop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dagda.py", line 35, in main
    r = execute_dagda_cmd(cmd=cmd, args=parsed_args)
  File "/home/sxue/project/dagda/dagda/cli/dagda_cli.py", line 43, in execute_dagda_cmd
    ds.run()
  File "/home/sxue/project/dagda/dagda/api/dagda_server.py", line 101, in run
    self.sysdig_falco_monitor.pre_check()
  File "/home/sxue/project/dagda/dagda/analysis/runtime/sysdig_falco_monitor.py", line 97, in pre_check
    self.docker_driver.docker_stop(container_id)
  File "/home/sxue/project/dagda/dagda/driver/docker_driver.py", line 110, in docker_stop
    self.cli.stop(container=container_id)
  File "/home/sxue/anaconda3/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/sxue/anaconda3/lib/python3.7/site-packages/docker/api/container.py", line 1134, in stop
    self._raise_for_status(res)
  File "/home/sxue/anaconda3/lib/python3.7/site-packages/docker/api/client.py", line 248, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/sxue/anaconda3/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Multiple IDs found with provided prefix: 09b61f6b45dde38ebd925697f418386f8f01ccf3029b08985b65a11eebbcb91e")
```

### On which platforms did you notice this:

Please complete the following information:

 - OS: Ubuntu16.04
 - OS Version: [e.g. (~$ uname -a)]
 - Python version: Python 3.7.0
 - Docker version: Version: 18.03.0-ce
 - MongoDB version : 4.0.6（lastest）

Btw, is there any log file for dagda, I run the command with option -d, the bug log print on the terminal.

Thanks for your help :)

**Comment by axiqia** [comment]
It may be caused by I started dagda server before and I shut it down by` Ctrl +C`, while the` sysdig/falco` container was still running. 
I  stopped `sysdig/falco` container and then everything works well.
