### ISSUE TITLE
docker image scan with dagda in standalone server mode.

### ISSUE THREAD

**Issue by yyosioka** [eliasgranderubio/dagda#84]
### Short description
I want to run a docker image scan with dagda in standalone server mode.
Please tell me the correct procedure.

This was done with reference to the following pages
https://hub.docker.com/r/3grander/dagda

### Reproduction steps

1. Install the software
2 $docker pull mongo
3 $docker run -d -p 27017:27017 mongo
4 $docker pull 3grander/dagda:0.8.0
5 $export VULNDB_HOST=10.0.x.xx :my pc adress
6 $export VULNDB_PORT=27017
7 $export DAGDA_HOST=0.0.0.0
8 $export DAGDA_PORT=5000
9 $docker run -p $DAGDA_PORT:$DAGDA_PORT -v /var/run/docker.sock:/var/run/docker.sock:ro -v /tmp:/tmp:ro 3grander/dagda:0.8.0 start -s $DAGDA_HOST -p $DAGDA_PORT -m $VULNDB_HOST -mp $VULNDB_PORT
10 $docker exec -it adoring_hundle python3 dagda.py start -m 10.0.x.xx

### Expected results
Success.

### Actual results
The following error occurs on No10
----------------------------------------------------------------------------------------------
<2020-07-16 09:01:00,790> <ERROR> <DagdaServer> <dagda> <main:46> <[Errno 98] Address in use>
Traceback (most recent call last):
  File "dagda.py", line 35, in main
    r = execute_dagda_cmd(cmd=cmd, args=parsed_args)
  File "/opt/app/cli/dagda_cli.py", line 43, in execute_dagda_cmd
    ds.run()
  File "/opt/app/api/dagda_server.py", line 113, in run
    serve(DagdaServer.app, host=self.dagda_server_host, port=self.dagda_server_port, ident=None)
  File "/usr/local/lib/python3.6/site-packages/waitress/__init__.py", line 12, in serve
    server = _server(app, **kw)
  File "/usr/local/lib/python3.6/site-packages/waitress/server.py", line 88, in create_server
    sockinfo=sockinfo,
  File "/usr/local/lib/python3.6/site-packages/waitress/server.py", line 239, in __init__
    self.bind_server_socket()
  File "/usr/local/lib/python3.6/site-packages/waitress/server.py", line 368, in bind_server_socket
    self.bind(sockaddr)
  File "/usr/local/lib/python3.6/site-packages/waitress/wasyncore.py", line 398, in bind
    return self.socket.bind(addr)
OSError: [Errno 98] Address in use

### On which platforms did you notice this:
ubuntsu 18.0.4
Please complete the following information:

 - OS: [Ubuntu]
 - OS Version: [18.0.4]
 - Python version: [Python 3.6.9]
 - Docker version [Docker version 19.03.12]

### 

> 

> [Solution]

A possible solution for this issue would be '...'

**Comment by yyosioka** [comment]
I solved it so I will close it
