### ISSUE TITLE
Error while starting dagda (TypeError: an integer is required - got type bytes)

### ISSUE THREAD

**Issue by bhumish** [eliasgranderubio/dagda#89]
### Short description

I was trying to start dagda with the command `sudo python3 dagda.py start` or `python3 dagda.py start` after installing all the dependencies. It gives an error related to integer/bytes.

### Reproduction steps

Follow every step (pre-requisites) to install and start dagda:
Python3, MongoDB, Docker are higher versions than listed.
Installed all the requirements using pip3
Installed kernel-headers
Installed sysdig
Used sudo to install all the above packages

Getting error while trying to start dagda.py using sudo or normal-user

### Expected results

dagda should start

### Actual results

TypeError: an integer is required (got type bytes)

### On which platforms did you notice this:

Please complete the following information:

 - OS: [Ubuntu 20.04 x86_64]
 - OS Version: [Linux 5.4.0-42-generic]
 - Python version: [Python 3.8.3]
 - Docker version [19.03.8]
 - MongoDB version [4.4.1]

### Backtrace

```
<2020-09-18 20:06:42,866> <ERROR> <DagdaServer> <dagda> <main:46> <an integer is required (got type bytes)>
Traceback (most recent call last):
  File "dagda.py", line 35, in main
    r = execute_dagda_cmd(cmd=cmd, args=parsed_args)
  File "/home/bhumish/github-tools/dagda/dagda/cli/dagda_cli.py", line 32, in execute_dagda_cmd
    from api.dagda_server import DagdaServer
  File "/home/bhumish/github-tools/dagda/dagda/api/dagda_server.py", line 33, in <module>
    from vulnDB.db_composer import DBComposer
  File "/home/bhumish/github-tools/dagda/dagda/vulnDB/db_composer.py", line 30, in <module>
    from vulnDB.bid_downloader import bid_downloader
  File "/home/bhumish/github-tools/dagda/dagda/vulnDB/bid_downloader.py", line 23, in <module>
    from joblib import Parallel, delayed
  File "/usr/local/lib/python3.8/dist-packages/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 32, in <module>
    from .externals.cloudpickle import dumps, loads
  File "/usr/local/lib/python3.8/dist-packages/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/usr/local/lib/python3.8/dist-packages/joblib/externals/cloudpickle/cloudpickle.py", line 151, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/usr/local/lib/python3.8/dist-packages/joblib/externals/cloudpickle/cloudpickle.py", line 132, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)

```

### Solution

Need to find solution

Update: read at some places that python3.8 is not supported for xyz pip packages. It was suggested to downgrade to python3.7 -- I will downgrade mine and modify this thread if there are any updates.

**Comment by alec-downey** [comment]
Hi I also have this issue, did you ever find a solution?

**Comment by MartinThoma** [comment]
I had the same issue. I now use `Python 3.7.8` via [pyenv](https://github.com/pyenv/pyenv) and it works.

**Comment by jakobkuehl** [comment]
The cloudpickle Library changed from Python 3.7 to 3.8. Therefore this Error will happen if you use a Python version > 3.7

**Comment by eliasgranderubio** [comment]
I've just updated Dagda to work with Python 3.8.
